import pandas as pd


columns = ['id', 'company_name', 'date', 'rlos_number', 'lead_number', 'lan_number', 'reject_hold', 'customer_name', 'location', 'type', 'department_type', 'price', 'remarks', 'branch', 'id', 'company_name', 'date', 'aps_id', 'customer_name', 'property_address', 'type', 'search_number', 'rm_name', 'price', 'remarks', 'id', 'company_name', 'date', 'loan_application_number', 'name_of_borrower', 'gst_number', 'place_of_supply', 'type', 'product_type', 'price', 'subject_to_reverse_charge', 'remarks', 'id', 'company_name', 'customer_name', 'date', 'deal_number', 'branch', 'address_of_property', 'type', 'price', 'remarks', 'id', 'company_name', 'date', 'customer_name', 'party_address', 'gst_number_party', 'delivery_address', 'gst_number_delivery', 'application_number', 'branch', 'type', 'price', 'remarks', 'id', 'company_name', 'company_address', 'date', 'gst_number', 'branch', 'customer_name', 'address', 'type', 'price', 'remarks', 'id', 'company_name', 'date', 'address_line_1', 'address_line_2', 'address_line_3', 'subject', 'name_of_applicant', 'type', 'price', 'remarks', 'id', 'company_name', 'date', 'address_line_1', 'address_line_2', 'customer_name', 'aps_number', 'village', 'survey_number', 'type', 'price', 'remarks', 'id', 'company_name', 'date', 'branch', 'name_of_applicant', 'address', 'type', 'price', 'remarks', 'id', 'company_name', 'date', 'company_address', 'name_of_applicant', 'aps', 'type', 'price', 'remarks', 'id', 'company_name', 'date', 'aps_number', 'location', 'customer_name', 'distance', 'request_received_date', 'repost_submitted_date', 'sro_1', 'sro_2', 'type', 'price', 'remarks', 'id', 'company_name', 'date', 'company_address', 'company_gst_number', 'product_type', 'product_price', 'type', 'price', 'r_m_fpr_name', 'invoice_status', 'id', 'company_name', 'date', 'company_address', 'company_gst_number', 'product_type', 'initiator_name', 'initiation_date', 'location', 'type_of_service', 'service_price', 'type', 'price', 'property_address', 'client_name', 'remarks', 'id', 'company_name', 'date', 'company_address', 'company_gst_number', 'initiator_name', 'initiation_date', 'location', 'type_of_service', 'service_price', 'type', 'price', 'property_address', 'client_name', 'pocket_expense', 'remarks', 'id', 'company_name', 'date', 'company_zone', 'company_location', 'company_branch', 'verification_type', 'co_name', 'verification_rate', 'number_of_verification', 'aps_id', 'customer_name', 'property_address', 'remarks', 'id', 'company_name', 'date', 'company_address', 'case_number', 'name_of_party', 'court_stamp_fee', 'advocate_fee', 'clerk_fee', 'expenses', 'travelling_expenses', 'other_expenses', 'remarks', 'id', 'company_name', 'customer_name', 'village', 'price']
myset = sorted(set(columns))
data = pd.DataFrame(columns=list(myset))
print(data)



