# Generated by Django 4.2.1 on 2023-06-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Agri Bank', max_length=100)),
                ('customer_name', models.CharField(default='', max_length=100)),
                ('village', models.CharField(default='', max_length=100)),
                ('price', models.PositiveSmallIntegerField(default=1000)),
            ],
            options={
                'verbose_name_plural': 'AgriBank',
            },
        ),
    ]
