# Generated by Django 4.2.1 on 2023-06-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0002_agribank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poonawalla',
            old_name='pg_number',
            new_name='loan_application_number',
        ),
        migrations.AddField(
            model_name='au',
            name='branch',
            field=models.CharField(default='Himmatnagar', max_length=12),
        ),
    ]
