# Generated by Django 4.2.1 on 2023-06-29 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0003_rename_pg_number_poonawalla_loan_application_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cholamandalam',
            old_name='Rm_name',
            new_name='rm_name',
        ),
    ]
