# Generated by Django 4.2.1 on 2023-06-29 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0004_rename_rm_name_cholamandalam_rm_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cholamandalam',
            old_name='APS_ID',
            new_name='aps_id',
        ),
    ]
