# Generated by Django 4.2.1 on 2023-07-01 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Invoice', '0006_personaldetails_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='created_by',
        ),
        migrations.AddField(
            model_name='cholamandalam',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
